import java.io.BufferedReader;
import java.util.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;

public class Extractcds {
    public static void main(String[] args) {

        String i = "ATGGAGAAAGAGGTAACAGAGAGCTTGCAACAAACTCGAATGGATCTGGGTAGGGAAAATGTGGATCCGGGAAAAGACAAGGGTCAAGGGGTAGTTGAAGATCATTTAATGTATAGAGCTACTGAACATAGAGGGTCAGAGGCTAGCTATTCAGCAGCAGAAAGGCCAGTGGTCAACATCACAAGTTATGGGGAAGAGGCAAAAAGAGCGGGAAAGAAGACTGAAGAAGGAAAAAAGAGGGAATCAAAACTTCAAAGTGACGCTTTAAAGGAAAAAATGATTTTTAAAAACAAAAAAGAGTTGAATGAGGAGCGGGAAATGAACTGGAGCAATAACAAGCAAAAAGAAATTATGGGCTCTCAACACAAAGAAGCAAACATGGGCCAAATGGAATTAGAAGCTGAGGATGGAGTTAATGAGCCATATGCAAATAAGTGTAAGCCCATAAGGAGAAAGTGGAAGTCTCAAGCCCGCAATTTAGAAGAAAAATGGAAGAGCAAAGAGGGGCAAGTTGTAGCAATAAGGGAGAAACAACAAGATCCAATGGAGAAAGAGGTAACAGAGAGCTTGCAACAAACTCGAATGGATCTGGGTAGGGAAAATGTGGATCCGGGAAAAGACAAGGGTCAAGGGGTAGTTGAAGATCATTTAATGTATAGAGCTACTGAACATAGAGGGTCAGAGGCTAGCTATTCAGCAGCAGAAAGGCCAGTGGTCAACATCACAAGTTATGGGGAAGAGGCAAAAAGAGCGGGAAAGAAGACTGAAGAAGGAAAAAAGAGGGAATCAAAACTTCAAAGTGACGCTTTAAAGGAAAAAATGATTTTTAAAAACAAAAAAGAGTTGAATGAGGAGCGGGAAATGAACTGGAGCAATAACAAGCAAAAAGAAATTATGGGCTCTCAACACAAAGAAGCAAACATGGGCCAAATGGAATTAGAAGCTGAGGATGGAGTTAATGAGCCATATGCAAATAAGTGTAAGCCCATAAGGAGAAAGTGGAAGTCTCAAGCCCGCAATTTAGAAGAAAAAGGGAAGAGCAAAGAGGGGCAAGTTGTAAGGAAAAGGCCAGCAAGTTCTCAAAAATGCAACTCAGCTACAGCTTGA";
        System.out.println(i.length());
        try {
            BufferedReader linebr = new BufferedReader(new InputStreamReader(new FileInputStream(new File("/Users/shenzenan/Desktop/MSYJ/MSYJ.gene.models.gff3")),
                    "UTF-8"));
            String lineTxt = null;
            while ((lineTxt = linebr.readLine()) != null) {
                String[] array = lineTxt.split("\t");
                //System.out.println(array.length);
                if (array[2].endsWith("CDS")){

                }
            }
        }
        catch (Exception e){
            System.err.println("read errors :" + e);
        }

    }
}
